-- caso 1
SELECT 
    P.ID_PROFESIONAL AS "ID PROFESIONAL",
    P.APPATERNO || ' ' || P.APMATERNO || ' ' || P.NOMBRE AS "PROFESIONAL",
    SUM(CASE WHEN E.COD_SECTOR = 3 THEN 1 ELSE 0 END) AS "NRO ASESORIA BANCA",
    REPLACE(TO_CHAR(SUM(CASE WHEN E.COD_SECTOR = 3 THEN A.HONORARIO ELSE 0 END),'$999,999,999'),',','.') AS "MONTO_TOTAL_BANCA",
    SUM(CASE WHEN E.COD_SECTOR = 4 THEN 1 ELSE 0 END) AS "NRO ASESORIA RETAIL",
    REPLACE(TO_CHAR(SUM(CASE WHEN E.COD_SECTOR = 4 THEN A.HONORARIO ELSE 0 END),'$999,999,999'),',','.') AS "MONTO_TOTAL_RETAIL",
    COUNT(A.ID_PROFESIONAL) AS "TOTAL ASESORIAS",
    REPLACE(TO_CHAR(SUM(A.HONORARIO),'$999,999,999'),',','.') AS "TOTAL HONORARIOS"
FROM 
    PROFESIONAL P
JOIN 
    ASESORIA A ON P.ID_PROFESIONAL = A.ID_PROFESIONAL
JOIN 
    EMPRESA E ON A.COD_EMPRESA = E.COD_EMPRESA
WHERE 
    E.COD_SECTOR IN (3, 4)
GROUP BY 
    P.ID_PROFESIONAL, 
    P.APPATERNO, 
    P.APMATERNO, 
    P.NOMBRE
HAVING 
    SUM(CASE WHEN E.COD_SECTOR = 3 THEN 1 ELSE 0 END) > 0
    AND SUM(CASE WHEN E.COD_SECTOR = 4 THEN 1 ELSE 0 END) > 0
ORDER BY 
    P.ID_PROFESIONAL ASC;

--caso 2 creacion de tabla reporte mes y guardado de datos en ella
CREATE TABLE REPORTE_MES AS
SELECT 
    P.ID_PROFESIONAL AS "ID_PROF",
    P.APPATERNO || ' ' || P.APMATERNO || ' ' || P.NOMBRE AS "NOMBRE_COMPLETO",
    PR.NOMBRE_PROFESION AS "NOMBRE_PROFESION",
    C.NOM_COMUNA AS "COMUNA_RESIDENCIA",
    COUNT(A.ID_PROFESIONAL) AS "NRO_ASSESORIAS",
    ROUND(SUM(A.HONORARIO), 0) AS "MONTO_TOTAL_HONORARIOS",
    ROUND(AVG(A.HONORARIO), 0) AS "PROMEDIO_HONORARIO",
    MIN(A.HONORARIO) AS "HONORARIO_MINIMO",
    MAX(A.HONORARIO) AS "HONORARIO_MAXIMO"
FROM 
    PROFESIONAL P
JOIN 
    ASESORIA A ON P.ID_PROFESIONAL = A.ID_PROFESIONAL
JOIN 
    PROFESION PR ON P.COD_PROFESION = PR.COD_PROFESION
JOIN 
    COMUNA C ON P.COD_COMUNA = C.COD_COMUNA
WHERE 
    EXTRACT(YEAR FROM A.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1
    AND EXTRACT(MONTH FROM A.FIN_ASESORIA) = 4
GROUP BY 
    P.ID_PROFESIONAL, 
    P.APPATERNO, 
    P.APMATERNO, 
    P.NOMBRE, 
    PR.NOMBRE_PROFESION, 
    C.NOM_COMUNA
ORDER BY 
    P.ID_PROFESIONAL ASC;


--caso3
--consulta antes del UPDATE
SELECT 
SUM(A.HONORARIO) AS "HONORARIO",
    P.ID_PROFESIONAL AS "ID PROFESIONAL",
    P.NUMRUN_PROF AS "NUMERO PROF",
    P.SUELDO AS "SUELDO"
FROM 
    PROFESIONAL P
JOIN 
    ASESORIA A ON P.ID_PROFESIONAL = A.ID_PROFESIONAL
WHERE 
    EXTRACT(YEAR FROM A.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1
    AND EXTRACT(MONTH FROM A.FIN_ASESORIA) = 3
GROUP BY 
    P.ID_PROFESIONAL, P.NUMRUN_PROF, P.SUELDO
ORDER BY 
    P.ID_PROFESIONAL;
   
    --UPDATE para la actualizacion de sueldos correspondiente 
UPDATE PROFESIONAL P
SET P.SUELDO = 
    CASE
        WHEN (SELECT SUM(A.HONORARIO)
              FROM ASESORIA A
              WHERE A.ID_PROFESIONAL = P.ID_PROFESIONAL
              AND EXTRACT(YEAR FROM A.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1
              AND EXTRACT(MONTH FROM A.FIN_ASESORIA) = 3) < 1000000 THEN P.SUELDO * 1.1
        ELSE P.SUELDO * 1.15
    END;

UPDATE PROFESIONAL P
SET P.PUNTAJE = 
    CASE
        WHEN (SELECT SUM(A.HONORARIO)
              FROM ASESORIA A
              WHERE A.ID_PROFESIONAL = P.ID_PROFESIONAL
              AND EXTRACT(YEAR FROM A.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1
              AND EXTRACT(MONTH FROM A.FIN_ASESORIA) = 3) < 1000000 THEN 10
        ELSE 15
    END
WHERE 
    P.ID_PROFESIONAL IN (SELECT A.ID_PROFESIONAL
    FROM ASESORIA A
        WHERE EXTRACT(YEAR FROM A.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1
            AND EXTRACT(MONTH FROM A.FIN_ASESORIA) = 3); 

--consulta despues de la actualizacion de sueldos 
 SELECT 
    SUM(A.HONORARIO) AS "HONORARIO",
    P.ID_PROFESIONAL AS "ID PROFESIONAL",
    P.NUMRUN_PROF AS "NUMERO PROF",
    P.SUELDO AS "SUELDO"
FROM 
    PROFESIONAL P
JOIN 
    ASESORIA A ON P.ID_PROFESIONAL = A.ID_PROFESIONAL
WHERE 
    EXTRACT(YEAR FROM A.FIN_ASESORIA) = EXTRACT(YEAR FROM SYSDATE) - 1
    AND EXTRACT(MONTH FROM A.FIN_ASESORIA) = 3
GROUP BY 
    P.ID_PROFESIONAL, P.NUMRUN_PROF, P.SUELDO
ORDER BY 
    P.ID_PROFESIONAL;